-- BrewMaster Admin Supabase schema and seed data.
-- Run this in Supabase SQL Editor for a fresh development database.
-- Security note:
-- - RLS is enabled on every table.
-- - The anon write policies below are for this project's temporary development mode only,
--   because the current app still uses mock login instead of Supabase Auth.
-- - Before production, remove anon write policies and replace them with authenticated
--   role-based policies backed by Supabase Auth + profiles.role.
-- - Never put a service_role key or database password in frontend code.

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null check (price >= 0),
  status text not null check (status in ('on_sale', 'sold_out')),
  stock integer not null default 0 check (stock >= 0),
  category text not null check (category in ('beans', 'espresso', 'drip_bag', 'instant', 'gear')),
  origin text not null default '',
  roast_level text not null check (roast_level in ('light', 'medium', 'dark')),
  description text not null default '',
  recommended boolean not null default false,
  low_stock_threshold integer not null default 12,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists inventory_logs (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  type text not null check (type in ('in', 'out', 'adjust', 'restore')),
  change integer not null,
  before_stock integer not null,
  after_stock integer not null,
  reason text not null default '',
  operator text not null default 'Admin',
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_no text not null unique,
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_remark text not null default '',
  total_amount integer not null default 0 check (total_amount >= 0),
  status text not null check (status in ('pending', 'paid', 'shipped', 'completed', 'cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  product_name text not null,
  price integer not null check (price >= 0),
  count integer not null check (count > 0)
);

create table if not exists order_logs (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  action text not null,
  operator text not null default 'Admin',
  created_at timestamptz not null default now()
);

create table if not exists sales_channels (
  id bigint generated by default as identity primary key,
  name text not null,
  value integer not null default 0,
  color text not null default '#409eff',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  role text not null default 'staff' check (role in ('admin', 'staff')),
  permissions text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_products_active_created_at on products (is_active, created_at desc);
create index if not exists idx_products_status on products (status);
create index if not exists idx_products_category on products (category);
create index if not exists idx_orders_created_at on orders (created_at desc);
create index if not exists idx_orders_status on orders (status);
create index if not exists idx_order_items_order_id on order_items (order_id);
create index if not exists idx_order_logs_order_id on order_logs (order_id);
create index if not exists idx_inventory_logs_created_at on inventory_logs (created_at desc);

alter table products enable row level security;
alter table inventory_logs enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;
alter table order_logs enable row level security;
alter table sales_channels enable row level security;
alter table profiles enable row level security;

drop policy if exists "dev anon select products" on products;
drop policy if exists "dev anon write products" on products;
drop policy if exists "dev anon select inventory_logs" on inventory_logs;
drop policy if exists "dev anon write inventory_logs" on inventory_logs;
drop policy if exists "dev anon select orders" on orders;
drop policy if exists "dev anon write orders" on orders;
drop policy if exists "dev anon select order_items" on order_items;
drop policy if exists "dev anon write order_items" on order_items;
drop policy if exists "dev anon select order_logs" on order_logs;
drop policy if exists "dev anon write order_logs" on order_logs;
drop policy if exists "dev anon select sales_channels" on sales_channels;
drop policy if exists "dev anon write sales_channels" on sales_channels;

create policy "dev anon select products" on products for select to anon using (true);
create policy "dev anon write products" on products for all to anon using (true) with check (true);
create policy "dev anon select inventory_logs" on inventory_logs for select to anon using (true);
create policy "dev anon write inventory_logs" on inventory_logs for all to anon using (true) with check (true);
create policy "dev anon select orders" on orders for select to anon using (true);
create policy "dev anon write orders" on orders for all to anon using (true) with check (true);
create policy "dev anon select order_items" on order_items for select to anon using (true);
create policy "dev anon write order_items" on order_items for all to anon using (true) with check (true);
create policy "dev anon select order_logs" on order_logs for select to anon using (true);
create policy "dev anon write order_logs" on order_logs for all to anon using (true) with check (true);
create policy "dev anon select sales_channels" on sales_channels for select to anon using (true);
create policy "dev anon write sales_channels" on sales_channels for all to anon using (true) with check (true);

truncate table order_logs, order_items, orders, inventory_logs, sales_channels, products restart identity cascade;

insert into products
  (name, price, status, stock, category, origin, roast_level, description, recommended, low_stock_threshold, is_active, created_at)
select
  (array[
    '埃塞俄比亚耶加雪菲',
    '哥伦比亚花月夜',
    '危地马拉安提瓜',
    '巴拿马瑰夏',
    '巴西皇后庄园',
    '云南普洱日晒',
    '冷萃咖啡液礼盒',
    '精品挂耳组合',
    '意式拼配黑巧',
    '手冲滤杯套装'
  ])[((i - 1) % 10) + 1] || ' ' || i,
  2800 + i * 180,
  case when i % 5 = 0 then 'sold_out' else 'on_sale' end,
  case when i % 7 = 0 then 5 + i else 18 + i end,
  (array['beans', 'espresso', 'drip_bag', 'instant', 'gear'])[((i - 1) % 5) + 1],
  (array['埃塞俄比亚', '哥伦比亚', '危地马拉', '中国云南', '巴西'])[((i - 1) % 5) + 1],
  case when i % 3 = 0 then 'light' when i % 3 = 1 then 'medium' else 'dark' end,
  '风味干净，适合日常出杯和门店陈列。',
  i % 4 = 0,
  12,
  true,
  now() - (i || ' days')::interval
from generate_series(1, 28) as i;

insert into sales_channels (name, value, color, sort_order) values
  ('小程序', 42, '#409eff', 1),
  ('门店扫码', 31, '#67c23a', 2),
  ('外卖平台', 19, '#e6a23c', 3),
  ('社群团购', 8, '#f56c6c', 4);

insert into orders
  (order_no, customer_name, customer_phone, customer_address, customer_remark, total_amount, status, created_at)
select
  'ORDER' || (20260000 + i),
  '客户' || (i + 1),
  '1380000' || lpad((i + 1)::text, 4, '0'),
  '门店自提',
  '',
  floor(random() * 100000)::integer + 3000,
  (array['pending', 'paid', 'shipped', 'completed', 'cancelled'])[(i % 5) + 1],
  now() - (i || ' days')::interval
from generate_series(0, 54) as i;

insert into order_items (order_id, product_id, product_name, price, count)
select
  o.id,
  p1.id,
  p1.name,
  p1.price,
  1
from orders o
join lateral (
  select *
  from products
  where id = ((o.id - 1) % 28) + 1
) p1 on true;

insert into order_items (order_id, product_id, product_name, price, count)
select
  o.id,
  p2.id,
  p2.name,
  p2.price,
  2
from orders o
join lateral (
  select *
  from products
  where id = ((o.id + 6) % 28) + 1
) p2 on true;

update orders o
set total_amount = item_totals.total_amount
from (
  select order_id, sum(price * count)::integer as total_amount
  from order_items
  group by order_id
) item_totals
where o.id = item_totals.order_id;

insert into order_logs (order_id, action, operator, created_at)
select id, '创建订单', '系统', created_at
from orders;

insert into inventory_logs
  (product_id, product_name, type, change, before_stock, after_stock, reason, operator, created_at)
select
  id,
  name,
  'in',
  stock,
  0,
  stock,
  '初始 seed 入库',
  '系统',
  created_at
from products;
